# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/YoonD43/SEGU-Land"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/watch?v=6GQV6lhwgNs"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/YoonD43/SEGU-Land"
supportLink = "https://github.com/YoonD43/SEGU-Land/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SEGU-Land"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
